In [1]:
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = 'all' #默认为'last'

官方文档：
https://pytorch.org/docs/stable/generated/torch.nn.RNN.html

In [2]:
import torch
import torchvision
from torch import nn

In [27]:
trainset = torchvision.datasets.MNIST('./MNISTdata2/',
                                     transform=torchvision.transforms.ToTensor())
                                     #download=True)
data_loader = torch.utils.data.DataLoader(trainset,batch_size = 4)

In [40]:
type(trainset.train_data)
trainset.train_data.size()

torch.Tensor

torch.Size([60000, 28, 28])

In [32]:
for i,data in enumerate(data_loader):
    if i==1:
        print(data[0])
        print(data[0].size())

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
    

![jupyter](./pics/LSTM_formula.jpg)

![jupyter](./pics/LSTM_parameters.jpg)

![jupyter](./pics/LSTM_outputs.jpg)

In [13]:
#官方文档中的例子：

rnn = nn.LSTM(10, 20, 2)  #input_size：10，hidden_size：20，两层LSTM；
input = torch.randn(5, 3, 10)  #seq_len：5，batch：3，input_size：10
h0 = torch.randn(2, 3, 20)  #layer_num：2，batch：3，hidden_size：20
c0 = torch.randn(2, 3, 20)  
output, (hn, cn) = rnn(input, (h0, c0))
output
output.size()
#output：(seq_len,batch,hidden_size)，（5，3，20）
#注意这里输出没有再进行线性变换，所以输出的维数与隐藏状态的维数是一样的。

tensor([[[ 0.3328,  0.3045,  0.4220,  0.1886, -0.4886,  0.2109, -0.0916,
           0.3310,  0.0517,  0.0819, -0.7193, -0.0687,  0.7380, -0.0205,
          -0.0478,  0.0347,  0.3046, -0.1890,  0.1206,  0.3730],
         [-0.0605,  0.5441,  0.0014,  0.0230, -0.1283, -0.4568, -0.0102,
          -0.0758,  0.1814, -0.2447, -0.1990, -0.1460,  0.2621,  0.2209,
          -0.0501, -0.0856, -0.3456,  0.1105,  0.2900, -0.0493],
         [ 0.1685, -0.0151,  0.0681,  0.2222, -0.1754,  0.2434,  0.4500,
           0.3014, -0.0464, -0.0817,  0.0868, -0.0448,  0.3186,  0.0192,
          -0.3235,  0.0871,  0.1068, -0.4864,  0.3547, -0.0885]],

        [[ 0.2386,  0.1256,  0.1105,  0.1029, -0.3401,  0.2743, -0.0969,
           0.2890,  0.0638,  0.0988, -0.3004,  0.0345,  0.3122,  0.0506,
          -0.0316,  0.0844,  0.1638, -0.0668,  0.0454,  0.2300],
         [-0.0182,  0.3704,  0.0250,  0.0215, -0.1145, -0.1665, -0.0885,
          -0.0010,  0.1397, -0.0327, -0.0534, -0.0711,  0.3707,  0.1409,
        

torch.Size([5, 3, 20])

In [19]:
#https://pytorch.org/docs/stable/nn.html?highlight=lstm#torch.nn.LSTM
#注意参数，LSTM的参数包括两个矩阵，两个偏置向量，
#维数分别为：input_size * (4*hidden_size), hidden_size * (4*hidden_size)
#4*hidden_size,4*hidden_size
#另外两个是额外的（RNN初始化函数最后一行）的输出线性层的4*2矩阵和一个二维偏置向量。

class RNN(nn.Module):
    def __init__(self):
        super(RNN,self).__init__()
        self.rnn = nn.LSTM(input_size=3, #28,
                          hidden_size=4, #64,
                          num_layers=1,
                          batch_first=True)
        
        self.out = nn.Linear(4,2)#(64,10)
        
    def forward(self,x):
        r_out,(h_n, h_c) = self.rnn(x)
        out = self.out(r_out[:,-1,:])  #这里跟官方文档不一致，官方文档第二维是batch_size
        #out = self.out(r_out)
        return out
    
rnn = RNN()

In [ ]:
list(rnn.parameters())

官方文档中，LSTM类的参数为：

* input_size：输入x中包含多少个特征；

* hidden_size：隐藏状态h中包含多少个特征；

* num_layders：recurrent层的数量。例如，如果设置为2，那么表示两个LSTM堆叠在一起，形成一个stacked LSTM，默认为1；

* bias：如果设为false，那么层不应用bias权重b_ih和b_hh。默认为True。



In [20]:
#官方文档中，要求输入的
#根据这个实验，输出是（10，2），
#判断输入的第一维是batch_size；第二维是seq_len，第三维是input_size；

testinput = torch.randn(10,4,3)
out = rnn(testinput)
out

tensor([[-0.0398, -0.3878],
        [-0.0384, -0.3705],
        [-0.0194, -0.3579],
        [-0.0261, -0.3714],
        [ 0.0292, -0.3386],
        [-0.0493, -0.4011],
        [ 0.0189, -0.3583],
        [-0.0335, -0.4006],
        [-0.0736, -0.4474],
        [-0.1571, -0.4904]], grad_fn=<AddmmBackward>)

In [36]:
a = torch.randn(3,4,5)
a.size()
a
b = a[:,0,:]
b.size()
b
a.size()[0]
c = a.view(6,-1)
c.size()

torch.Size([3, 4, 5])

tensor([[[-0.6642,  1.8331,  2.1584,  0.3587,  1.2044],
         [ 1.3660,  1.3139, -1.3892, -0.6083, -1.6212],
         [ 0.6929, -0.5200,  1.7226, -1.0205,  2.7657],
         [-0.7322,  0.3355,  0.3247,  0.6266, -1.4932]],

        [[ 1.0223, -0.8878, -0.4717,  1.9733, -0.8626],
         [ 0.4447,  0.0779,  0.7690,  0.1739, -1.4704],
         [-0.5244, -0.1656, -0.6172,  0.4475,  0.2278],
         [ 2.0990, -1.3353, -0.0277,  1.5316, -1.1284]],

        [[ 0.4707,  2.0543,  0.7990,  1.0356,  0.1714],
         [-0.8572, -1.4685, -0.3881, -0.8228,  0.8629],
         [ 0.6605,  1.6384,  0.8303,  0.2998,  0.4465],
         [-0.6487,  0.0146, -0.4917, -1.1392,  0.4077]]])

torch.Size([3, 5])

tensor([[-0.6642,  1.8331,  2.1584,  0.3587,  1.2044],
        [ 1.0223, -0.8878, -0.4717,  1.9733, -0.8626],
        [ 0.4707,  2.0543,  0.7990,  1.0356,  0.1714]])

3

torch.Size([6, 10])

In [24]:
torch.max(b,1)

torch.return_types.max(
values=tensor([ 0.7073,  1.4311, -0.1145]),
indices=tensor([1, 2, 1]))

参考程序：

In [ ]:
import torch
from torch import nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt


# torch.manual_seed(1)    # reproducible

# Hyper Parameters
EPOCH = 1               # train the training data n times, to save time, we just train 1 epoch
BATCH_SIZE = 16
TIME_STEP = 28          # rnn time step / image height
INPUT_SIZE = 28         # rnn input size / image width
LR = 0.01               # learning rate
DOWNLOAD_MNIST = False   # set to True if haven't download the data


# Mnist digital dataset
train_data = dsets.MNIST(
    root='./MNIST_data',
    train=True,                         # this is training data
    transform=transforms.ToTensor(),    # Converts a PIL.Image or numpy.ndarray to
                                        # torch.FloatTensor of shape (C x H x W) and normalize in the range [0.0, 1.0]
    download=DOWNLOAD_MNIST,            # download it if you don't have it
)

# plot one example
print(train_data.train_data.size())     # (60000, 28, 28)
print(train_data.train_labels.size())   # (60000)
plt.imshow(train_data.train_data[0].numpy(), cmap='gray')
plt.title('%i' % train_data.train_labels[0])
plt.show()

# Data Loader for easy mini-batch return in training
train_loader = torch.utils.data.DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)

# convert test data into Variable, pick 2000 samples to speed up testing
test_data = dsets.MNIST(root='./MNIST_data', train=False, transform=transforms.ToTensor())
test_x = test_data.test_data.type(torch.FloatTensor)[:2000]/255.   # shape (2000, 28, 28) value in range(0,1)
test_y = test_data.test_labels.numpy()[:2000]    # covert to numpy array


class RNN(nn.Module):
    def __init__(self):
        super(RNN, self).__init__()

        self.rnn = nn.LSTM(         # if use nn.RNN(), it hardly learns
            input_size=INPUT_SIZE,
            hidden_size=64,         # rnn hidden unit
            num_layers=1,           # number of rnn layer
            batch_first=True,       # input & output will has batch size as 1s dimension. e.g. (batch, time_step, input_size)
        )

        self.out = nn.Linear(64, 10)

    def forward(self, x):
        # x shape (batch, time_step, input_size)
        # r_out shape (batch, time_step, output_size)
        # h_n shape (n_layers, batch, hidden_size)
        # h_c shape (n_layers, batch, hidden_size)
        r_out, (h_n, h_c) = self.rnn(x, None)   # None represents zero initial hidden state

        # choose r_out at the last time step
        out = self.out(r_out[:, -1, :])
        return out


rnn = RNN()
print(rnn)

optimizer = torch.optim.Adam(rnn.parameters(), lr=LR)   # optimize all cnn parameters
loss_func = nn.CrossEntropyLoss()                       # the target label is not one-hotted

# training and testing
for epoch in range(EPOCH):
    for step, (b_x, b_y) in enumerate(train_loader):        # gives batch data
        b_x = b_x.view(-1, 28, 28)              # reshape x to (batch, time_step, input_size)

        output = rnn(b_x)                               # rnn output
        loss = loss_func(output, b_y)                   # cross entropy loss
        optimizer.zero_grad()                           # clear gradients for this training step
        loss.backward()                                 # backpropagation, compute gradients
        optimizer.step()                                # apply gradients

        if step % 50 == 0:
            test_output = rnn(test_x)                   # (samples, time_step, input_size)
            pred_y = torch.max(test_output, 1)[1].data.numpy()
            accuracy = float((pred_y == test_y).astype(int).sum()) / float(test_y.size)
            print('Epoch: ', epoch, '| train loss: %.4f' % loss.data.numpy(), '| test accuracy: %.2f' % accuracy)

# print 10 predictions from test data
test_output = rnn(test_x[:10].view(-1, 28, 28))
pred_y = torch.max(test_output, 1)[1].data.numpy()
print(pred_y, 'prediction number')
print(test_y[:10], 'real number')