In [4]:
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = 'all' #默认为'last'

产生正弦数据：

numpy.random.randint(low, high=None, size=None, dtype='l')

函数的作用是，返回一个随机整型数，范围从低（包括）到高（不包括），即[low, high)。
如果没有写参数high的值，则返回[0,low)的值。

参数如下：

low: int
生成的数值最低要大于等于low。
（hign = None时，生成的数值要在[0, low)区间内）
high: int (可选)
如果使用这个值，则生成的数值在[low, high)区间。
size: int or tuple of ints(可选)
输出随机数的尺寸，比如size = (m * n* k)则输出同规模即m * n* k个随机数。默认是None的，仅仅返回满足要求的单一随机数。
dtype: dtype(可选)：
想要输出的格式。如int64、int等等
输出：

out: int or ndarray of ints
返回一个随机数或随机数数组。

In [14]:
start_test = np.random.randint(3,size=1)
start = np.random.randint(3,size=1)[0]
print(start_test)
print(start)

[0]
2


In [16]:
np.random.randint(3)

2

In [ ]:
np.random.randint(2, size=10)
np.random.randint(5, size=(2, 4))
np.random.randint(2, high=10, size=(2,3))

In [1]:
import torch.utils.data
from torch import optim,nn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
num_time_steps = 50
input_size = 1
hidden_size = 16
output_size = 1

In [17]:
start = np.random.randint(3,size=1)[0]
time_steps = np.linspace(start,start+10,num_time_steps)
print(time_steps)

[ 2.          2.20408163  2.40816327  2.6122449   2.81632653  3.02040816
  3.2244898   3.42857143  3.63265306  3.83673469  4.04081633  4.24489796
  4.44897959  4.65306122  4.85714286  5.06122449  5.26530612  5.46938776
  5.67346939  5.87755102  6.08163265  6.28571429  6.48979592  6.69387755
  6.89795918  7.10204082  7.30612245  7.51020408  7.71428571  7.91836735
  8.12244898  8.32653061  8.53061224  8.73469388  8.93877551  9.14285714
  9.34693878  9.55102041  9.75510204  9.95918367 10.16326531 10.36734694
 10.57142857 10.7755102  10.97959184 11.18367347 11.3877551  11.59183673
 11.79591837 12.        ]


In [21]:
data = np.sin(time_steps)
print(data)
print(data.shape)
data = data.reshape(num_time_steps,1)
print(data)
print(data.shape)

[ 0.90929743  0.80608763  0.6694212   0.50497047  0.31956097  0.1208881
 -0.08280223 -0.28305585 -0.47156126 -0.64049453 -0.7828441  -0.89270176
 -0.96550788 -0.99824062 -0.98954144 -0.93977138 -0.85099614 -0.72690035
 -0.57263459 -0.39460166 -0.2001908   0.00252898  0.20514378  0.3992441
  0.57677382  0.73036456  0.85364154  0.94148818  0.99025838  0.99792796
  0.96417857  0.890411    0.77968695  0.63660203  0.46709497  0.27820115
  0.07776061 -0.12590739 -0.3243496  -0.5093297  -0.67317009 -0.80907059
 -0.91139064 -0.97588346 -0.99987228 -0.98236145 -0.92407774 -0.82744023
 -0.69645984 -0.53657292]
(50,)
[[ 0.90929743]
 [ 0.80608763]
 [ 0.6694212 ]
 [ 0.50497047]
 [ 0.31956097]
 [ 0.1208881 ]
 [-0.08280223]
 [-0.28305585]
 [-0.47156126]
 [-0.64049453]
 [-0.7828441 ]
 [-0.89270176]
 [-0.96550788]
 [-0.99824062]
 [-0.98954144]
 [-0.93977138]
 [-0.85099614]
 [-0.72690035]
 [-0.57263459]
 [-0.39460166]
 [-0.2001908 ]
 [ 0.00252898]
 [ 0.20514378]
 [ 0.3992441 ]
 [ 0.57677382]
 [ 0.730364

In [24]:
print(data[:-1])

[[ 0.90929743]
 [ 0.80608763]
 [ 0.6694212 ]
 [ 0.50497047]
 [ 0.31956097]
 [ 0.1208881 ]
 [-0.08280223]
 [-0.28305585]
 [-0.47156126]
 [-0.64049453]
 [-0.7828441 ]
 [-0.89270176]
 [-0.96550788]
 [-0.99824062]
 [-0.98954144]
 [-0.93977138]
 [-0.85099614]
 [-0.72690035]
 [-0.57263459]
 [-0.39460166]
 [-0.2001908 ]
 [ 0.00252898]
 [ 0.20514378]
 [ 0.3992441 ]
 [ 0.57677382]
 [ 0.73036456]
 [ 0.85364154]
 [ 0.94148818]
 [ 0.99025838]
 [ 0.99792796]
 [ 0.96417857]
 [ 0.890411  ]
 [ 0.77968695]
 [ 0.63660203]
 [ 0.46709497]
 [ 0.27820115]
 [ 0.07776061]
 [-0.12590739]
 [-0.3243496 ]
 [-0.5093297 ]
 [-0.67317009]
 [-0.80907059]
 [-0.91139064]
 [-0.97588346]
 [-0.99987228]
 [-0.98236145]
 [-0.92407774]
 [-0.82744023]
 [-0.69645984]]


In [25]:
print(data[1:])

[[ 0.80608763]
 [ 0.6694212 ]
 [ 0.50497047]
 [ 0.31956097]
 [ 0.1208881 ]
 [-0.08280223]
 [-0.28305585]
 [-0.47156126]
 [-0.64049453]
 [-0.7828441 ]
 [-0.89270176]
 [-0.96550788]
 [-0.99824062]
 [-0.98954144]
 [-0.93977138]
 [-0.85099614]
 [-0.72690035]
 [-0.57263459]
 [-0.39460166]
 [-0.2001908 ]
 [ 0.00252898]
 [ 0.20514378]
 [ 0.3992441 ]
 [ 0.57677382]
 [ 0.73036456]
 [ 0.85364154]
 [ 0.94148818]
 [ 0.99025838]
 [ 0.99792796]
 [ 0.96417857]
 [ 0.890411  ]
 [ 0.77968695]
 [ 0.63660203]
 [ 0.46709497]
 [ 0.27820115]
 [ 0.07776061]
 [-0.12590739]
 [-0.3243496 ]
 [-0.5093297 ]
 [-0.67317009]
 [-0.80907059]
 [-0.91139064]
 [-0.97588346]
 [-0.99987228]
 [-0.98236145]
 [-0.92407774]
 [-0.82744023]
 [-0.69645984]
 [-0.53657292]]


In [28]:
x = torch.tensor(data[:-1]).float().view(1,num_time_steps-1,1)
y = torch.tensor(data[1:]).float().view(1,num_time_steps-1,1)
print(x)
print(x.shape)

tensor([[[ 0.9093],
         [ 0.8061],
         [ 0.6694],
         [ 0.5050],
         [ 0.3196],
         [ 0.1209],
         [-0.0828],
         [-0.2831],
         [-0.4716],
         [-0.6405],
         [-0.7828],
         [-0.8927],
         [-0.9655],
         [-0.9982],
         [-0.9895],
         [-0.9398],
         [-0.8510],
         [-0.7269],
         [-0.5726],
         [-0.3946],
         [-0.2002],
         [ 0.0025],
         [ 0.2051],
         [ 0.3992],
         [ 0.5768],
         [ 0.7304],
         [ 0.8536],
         [ 0.9415],
         [ 0.9903],
         [ 0.9979],
         [ 0.9642],
         [ 0.8904],
         [ 0.7797],
         [ 0.6366],
         [ 0.4671],
         [ 0.2782],
         [ 0.0778],
         [-0.1259],
         [-0.3243],
         [-0.5093],
         [-0.6732],
         [-0.8091],
         [-0.9114],
         [-0.9759],
         [-0.9999],
         [-0.9824],
         [-0.9241],
         [-0.8274],
         [-0.6965]]])
torch.Size([1, 49,

定义模型：

In [30]:
hidden_prev = torch.zeros(1, 1, hidden_size)
print(hidden_prev)
print(hidden_prev.shape)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
torch.Size([1, 1, 16])


In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.rnn = nn.RNN(input_size=input_size,hidden_size=hidden_size,
                          num_layers=1,batch_first=True)
        self.liner = nn.Linear(hidden_size,output_size)
        
    def forward(self,x,hidden_prev)